# Generated by Django 5.0.1 on 2024-02-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryandy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryandy',
            name='remaining_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
