# Generated by Django 5.0.1 on 2024-02-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryandy', '0002_inventoryandy_remaining_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryandy',
            name='remaining_quantity',
            field=models.IntegerField(),
        ),
    ]
