# Generated by Django 5.0.1 on 2024-02-16 11:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryandy', '0004_inventoryandy_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryandy',
            name='barcode',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
