# Generated by Django 5.0.1 on 2024-07-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryandy', '0005_alter_inventoryandy_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryandy',
            name='remaining_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventoryandy',
            name='sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
