# Generated by Django 5.0.1 on 2024-07-27 08:10

from django.db import migrations, models
import uuid


def generate_unique_barcode(apps, schema_editor):
    Inventoryandy = apps.get_model('inventoryandy', 'Inventoryandy')
    for item in Inventoryandy.objects.all():
        if not item.barcode:  # Only set if barcode is empty
            item.barcode = str(uuid.uuid4())  # Set a unique barcode
            item.save()
            
def reverse_generate_unique_barcode(apps, schema_editor):
    # This method is optional if you want to handle the reverse migration
    pass
class Migration(migrations.Migration):

    dependencies = [
        ('inventoryandy', '0006_alter_inventoryandy_remaining_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryandy',
            name='barcode',
            field=models.CharField(max_length=100, unique=True, blank=True, null=True),
        ),
        migrations.RunPython(generate_unique_barcode, reverse_code=migrations.RunPython.noop),
    ]
